#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORLDPLAY_DIR="${HAPPYOYSTER_DATA_ROOT:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"

TASK_IDS_VALUE="${1:-${TASK_IDS:-}}"
if [[ -z "$TASK_IDS_VALUE" ]]; then
  echo "Usage: ./run_task.sh GC079[,GC116]" >&2
  echo "Or: TASK_IDS=GC079 ./run_task.sh" >&2
  exit 2
fi

KEY_FILE="${AGENT_PLAYER_KEYS_FILE:-${SCRIPT_DIR}/../api_keys.sh}"
if [[ -f "$KEY_FILE" ]]; then
  # shellcheck source=/dev/null
  source "$KEY_FILE"
fi

RUN_ID_VALUE="${HAPPYOYSTER_RUN_ID:-worldplay_happyoyster_${TASK_IDS_VALUE//,/}_$(date +%Y%m%d_%H%M%S)}"
OUT_ROOT_VALUE="${HAPPYOYSTER_OUT_ROOT:-${WORLDPLAY_DIR}/output}"
LOG_PATH="${OUT_ROOT_VALUE}/${RUN_ID_VALUE}.log"
mkdir -p "${OUT_ROOT_VALUE}"

export HAPPYOYSTER_CDP_URL="${HAPPYOYSTER_CDP_URL:-http://127.0.0.1:9222}"
export HAPPYOYSTER_RUN_ID="$RUN_ID_VALUE"
export HAPPYOYSTER_DATA_ROOT="$WORLDPLAY_DIR"
export HAPPYOYSTER_OUT_ROOT="$OUT_ROOT_VALUE"
export HAPPYOYSTER_DATA_FILES="${HAPPYOYSTER_DATA_FILES:-GC:GC.json,IF:IF.json,OE:OE.json}"
export HAPPYOYSTER_TASK_FILE="${HAPPYOYSTER_TASK_FILE:-}"
export TASK_IDS="$TASK_IDS_VALUE"

export SKIP_EXISTING_SUCCESS="${SKIP_EXISTING_SUCCESS:-0}"
export CREATE_WAIT_TIMEOUT_S="${CREATE_WAIT_TIMEOUT_S:-600}"
export CREATE_ATTEMPTS="${CREATE_ATTEMPTS:-4}"
export CREATE_RETRY_DELAY_S="${CREATE_RETRY_DELAY_S:-20}"
export SUBMIT_READY_TIMEOUT_S="${SUBMIT_READY_TIMEOUT_S:-90}"
export DOWNLOAD_ATTEMPTS="${DOWNLOAD_ATTEMPTS:-3}"
export DOWNLOAD_MODAL_WAIT_S="${DOWNLOAD_MODAL_WAIT_S:-120}"
export DOWNLOAD_FILE_WAIT_S="${DOWNLOAD_FILE_WAIT_S:-90}"
export HAPPYOYSTER_ADAPTIVE_CORRECTION="${HAPPYOYSTER_ADAPTIVE_CORRECTION:-1}"
export HAPPYOYSTER_LIVE_HOLD_STOP_CHECK="${HAPPYOYSTER_LIVE_HOLD_STOP_CHECK:-1}"
export HAPPYOYSTER_LIVE_HOLD_REQUEST_MIN_MS="${HAPPYOYSTER_LIVE_HOLD_REQUEST_MIN_MS:-0}"
export HAPPYOYSTER_LIVE_HOLD_STOP_MIN_MS="${HAPPYOYSTER_LIVE_HOLD_STOP_MIN_MS:-600}"
export HAPPYOYSTER_LIVE_HOLD_MIN_REMAINING_MS="${HAPPYOYSTER_LIVE_HOLD_MIN_REMAINING_MS:-0}"
export HAPPYOYSTER_ADAPTIVE_PHASE_PROGRESS_CHECK="${HAPPYOYSTER_ADAPTIVE_PHASE_PROGRESS_CHECK:-1}"
export HAPPYOYSTER_ROTATION_LOOP_CHECK="${HAPPYOYSTER_ROTATION_LOOP_CHECK:-1}"
export HAPPYOYSTER_ROTATION_LOOP_MAX_ACTIONS="${HAPPYOYSTER_ROTATION_LOOP_MAX_ACTIONS:-4}"
export HAPPYOYSTER_ROTATION_LOOP_MAX_CHECKS="${HAPPYOYSTER_ROTATION_LOOP_MAX_CHECKS:-2}"
export HAPPYOYSTER_FINAL_ORIENTATION_CHECK="${HAPPYOYSTER_FINAL_ORIENTATION_CHECK:-1}"
export HAPPYOYSTER_FINAL_ORIENTATION_MAX_ACTIONS="${HAPPYOYSTER_FINAL_ORIENTATION_MAX_ACTIONS:-4}"
export HAPPYOYSTER_FINAL_ORIENTATION_MAX_CHECKS="${HAPPYOYSTER_FINAL_ORIENTATION_MAX_CHECKS:-2}"

echo "Run ID: ${HAPPYOYSTER_RUN_ID}"
echo "Task IDs: ${TASK_IDS}"
echo "Data root: ${HAPPYOYSTER_DATA_ROOT}"
echo "Task file: ${HAPPYOYSTER_TASK_FILE}"
echo "Data files: ${HAPPYOYSTER_DATA_FILES}"
echo "Output root: ${HAPPYOYSTER_OUT_ROOT}"
echo "CDP URL: ${HAPPYOYSTER_CDP_URL}"
echo "Claude adaptive controller: required"
echo "Log: ${LOG_PATH}"

python3 "${SCRIPT_DIR}/../player_happyoyster.py" 2>&1 | tee "$LOG_PATH"
