#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORLDPLAY_DIR="${GENIE3_DATA_ROOT:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"

TASK_IDS_VALUE="${1:-${TASK_IDS:-}}"
if [[ -z "$TASK_IDS_VALUE" ]]; then
  echo "Usage: ./run_task.sh GC079[,GC116]" >&2
  echo "Or: TASK_IDS=GC079 ./run_task.sh" >&2
  exit 2
fi

KEY_FILE="${AGENT_PLAYER_KEYS_FILE:-${SCRIPT_DIR}/../api_keys.sh}"
if [[ -f "$KEY_FILE" ]]; then
  # shellcheck source=/dev/null
  source "$KEY_FILE"
fi

RUN_ID_VALUE="${GENIE3_RUN_ID:-worldplay_rerun_${TASK_IDS_VALUE//,/}_$(date +%Y%m%d_%H%M%S)}"
OUT_ROOT_VALUE="${GENIE3_OUT_ROOT:-${WORLDPLAY_DIR}/output}"
RUN_LOG_ROOT_VALUE="${GENIE3_RUN_LOG_ROOT:-${OUT_ROOT_VALUE}-logs}"
LOG_PATH="${RUN_LOG_ROOT_VALUE}/${RUN_ID_VALUE}/runner.log"
mkdir -p "$(dirname "$LOG_PATH")"

export NODE_OPTIONS="${NODE_OPTIONS:---max-old-space-size=8192}"
export GENIE3_CDP_URL="${GENIE3_CDP_URL:-http://127.0.0.1:9223}"
export GENIE3_RUN_ID="$RUN_ID_VALUE"
export GENIE3_DATA_ROOT="$WORLDPLAY_DIR"
export GENIE3_OUT_ROOT="$OUT_ROOT_VALUE"
export GENIE3_RUN_LOG_ROOT="$RUN_LOG_ROOT_VALUE"
export GENIE3_DATA_FILES="${GENIE3_DATA_FILES:-GC:final_combined.json}"
export TASK_IDS="$TASK_IDS_VALUE"

export SKIP_EXISTING_SUCCESS="${SKIP_EXISTING_SUCCESS:-0}"
export SKIP_EXISTING_TERMINAL_FAILURE="${SKIP_EXISTING_TERMINAL_FAILURE:-0}"

export CREATE_WAIT_TIMEOUT_S="${CREATE_WAIT_TIMEOUT_S:-600}"
export POST_ACTION_WAIT_S="${POST_ACTION_WAIT_S:-300}"
export GENIE3_INITIAL_ACTION_DELAY_S="${GENIE3_INITIAL_ACTION_DELAY_S:-1}"
export GENIE3_ADAPTIVE_CORRECTION="${GENIE3_ADAPTIVE_CORRECTION:-1}"
export GENIE3_ADAPTIVE_PRETHINK="${GENIE3_ADAPTIVE_PRETHINK:-0}"
export GENIE3_ADAPTIVE_MAX_ACTIONS="${GENIE3_ADAPTIVE_MAX_ACTIONS:-3}"
export GENIE3_ADAPTIVE_PRE_PHASE_PLAN_MIN_MS="${GENIE3_ADAPTIVE_PRE_PHASE_PLAN_MIN_MS:-0}"
export GENIE3_ADAPTIVE_PHASE_DONE_CHECK="${GENIE3_ADAPTIVE_PHASE_DONE_CHECK:-1}"
export GENIE3_ADAPTIVE_PHASE_PROGRESS_CHECK="${GENIE3_ADAPTIVE_PHASE_PROGRESS_CHECK:-1}"
export GENIE3_ADAPTIVE_PHASE_CHECK_EVERY="${GENIE3_ADAPTIVE_PHASE_CHECK_EVERY:-3}"
export GENIE3_ADAPTIVE_EXTEND_HOLD="${GENIE3_ADAPTIVE_EXTEND_HOLD:-1}"
export GENIE3_ADAPTIVE_EXTEND_HOLD_MIN_MS="${GENIE3_ADAPTIVE_EXTEND_HOLD_MIN_MS:-2000}"
export GENIE3_LIVE_HOLD_STOP_CHECK="${GENIE3_LIVE_HOLD_STOP_CHECK:-1}"
export GENIE3_LIVE_HOLD_CHECK_INTERVAL_MS="${GENIE3_LIVE_HOLD_CHECK_INTERVAL_MS:-50}"
export GENIE3_LIVE_HOLD_MAX_CHECKS="${GENIE3_LIVE_HOLD_MAX_CHECKS:-20}"
export GENIE3_LIVE_HOLD_MIN_MS="${GENIE3_LIVE_HOLD_MIN_MS:-0}"
export GENIE3_LIVE_HOLD_MIN_APPLY_MS="${GENIE3_LIVE_HOLD_MIN_APPLY_MS:-600}"
export GENIE3_LIVE_HOLD_MIN_REMAINING_MS="${GENIE3_LIVE_HOLD_MIN_REMAINING_MS:-0}"
export GENIE3_ROTATION_LOOP_CHECK="${GENIE3_ROTATION_LOOP_CHECK:-1}"
export GENIE3_FINAL_ORIENTATION_CHECK="${GENIE3_FINAL_ORIENTATION_CHECK:-1}"
export GENIE3_ERROR_RETRIES="${GENIE3_ERROR_RETRIES:-3}"
export DOWNLOAD_EXPECT_TIMEOUT_MS="${DOWNLOAD_EXPECT_TIMEOUT_MS:-25000}"
export DOWNLOAD_JS_FALLBACK_TIMEOUT_MS="${DOWNLOAD_JS_FALLBACK_TIMEOUT_MS:-15000}"
export DOWNLOAD_SETTLE_MS="${DOWNLOAD_SETTLE_MS:-15000}"
export DOWNLOAD_CLICK_RETRIES="${DOWNLOAD_CLICK_RETRIES:-3}"

echo "Run ID: ${GENIE3_RUN_ID}"
echo "Task IDs: ${TASK_IDS}"
echo "Data root: ${GENIE3_DATA_ROOT}"
echo "Output root: ${GENIE3_OUT_ROOT}"
echo "CDP URL: ${GENIE3_CDP_URL}"
echo "Log: ${LOG_PATH}"

PYTHON_BIN="${GENIE3_PYTHON_BIN:-python3}"
"${PYTHON_BIN}" "${SCRIPT_DIR}/../player_genie3.py" 2>&1 | tee "$LOG_PATH"
